# ARG NODE_VERSION=20.16.0
# ARG ALPINE_VERSION=3.20

# FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS node

# FROM alpine:${ALPINE_VERSION} AS build-env

# COPY --from=node /usr/lib /usr/lib
# COPY --from=node /usr/local/lib /usr/local/lib
# COPY --from=node /usr/local/include /usr/local/include
# COPY --from=node /usr/local/bin /usr/local/bin

# RUN node -v

# #FROM alpine:3.18 AS build-env

# # Set the working directory in the container
# WORKDIR /usr/src/kryptomerchadmin

# # Copy package.json and package-lock.json to the container
# COPY package*.json ./

# # RUN npm install -g npm@latest
# # Install dependencies
# RUN npm install

# # Copy the rest of the application code to the container
# COPY . .

# # Define build arguments
# ARG REACT_APP_API_URL
# ARG REACT_APP_PROJECT_ID
# ARG REACT_APP_RELAY_URL
# ARG REACT_APP_KDA_NETWORK_TYPE
# ARG REACT_APP_KDA_CHAIN_ID
# ARG REACT_APP_KDA_GAS_PRICE
# ARG REACT_APP_KDA_GAS_LIMIT
# ARG REACT_APP_KDA_PRECISION
# ARG REACT_APP_KDA_NETWORK_ID
# ARG REACT_APP_KDA_FEE
# ARG REACT_APP_APR_FEE
# ARG REACT_APP_KDA_NETWORK
# ARG REACT_APP_BASE_URL
# ARG REACT_APP_ZELCORE_URL
# ARG REACT_APP_STRIPE_PUBLISHABLE_KEY


# # Set environment variables
# ENV REACT_APP_API_URL=$REACT_APP_API_URL \
#     REACT_APP_PROJECT_ID=$REACT_APP_PROJECT_ID \
#     REACT_APP_RELAY_URL=$REACT_APP_RELAY_URL \
#     REACT_APP_KDA_NETWORK_TYPE=$REACT_APP_KDA_NETWORK_TYPE \
#     REACT_APP_KDA_CHAIN_ID=$REACT_APP_KDA_CHAIN_ID \
#     REACT_APP_KDA_GAS_PRICE=$REACT_APP_KDA_GAS_PRICE \
#     REACT_APP_KDA_GAS_LIMIT=$REACT_APP_KDA_GAS_LIMIT \
#     REACT_APP_KDA_PRECISION=$REACT_APP_KDA_PRECISION \
#     REACT_APP_KDA_NETWORK_ID=$REACT_APP_KDA_NETWORK_ID \
#     REACT_APP_KDA_FEE=$REACT_APP_KDA_FEE \
#     REACT_APP_APR_FEE=$REACT_APP_APR_FEE \
#     REACT_APP_KDA_NETWORK=$REACT_APP_KDA_NETWORK \
#     REACT_APP_BASE_URL=$REACT_APP_BASE_URL \
#     REACT_APP_ZELCORE_URL=$REACT_APP_ZELCORE_URL \
#     REACT_APP_STRIPE_PUBLISHABLE_KEY=$REACT_APP_STRIPE_PUBLISHABLE_KEY



# # Build the React app
# RUN npm run build

# COPY . .


# FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION}

# # Install dependencies
#  RUN npm install -g npm@latest

# # Install serve
# RUN npm install -g serve

# # Copy build files from builder stage
# COPY --from=build-env /usr/src/kryptomerchadmin/build /usr/src/kryptomerchadmin/build

# # Command to run the app
# CMD ["serve", "-s", "/usr/src/kryptomerchadmin/build", "-l", "tcp://0.0.0.0:3000"]

# # Expose the desired port
# EXPOSE 3000




ARG NODE_VERSION=20.16.0
ARG ALPINE_VERSION=3.20

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS node

FROM alpine:${ALPINE_VERSION} AS build-env

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN node -v

WORKDIR /usr/src/kryptomerchadmin

COPY package*.json ./

RUN npm install

COPY . .

# Define build arguments
ARG REACT_APP_API_URL
ARG REACT_APP_PROJECT_ID
ARG REACT_APP_RELAY_URL
ARG REACT_APP_KDA_NETWORK_TYPE
ARG REACT_APP_BASE_URL
ARG REACT_APP_ZELCORE_URL
ARG REACT_APP_ADMIN_ADDRESS
ARG REACT_APP_STRIPE_PUBLISHABLE_KEY
ARG REACT_APP_WALLETCONNECT_BRIDGE_URL
ARG REACT_APP_WALLETCONNECT_CHAIN_ID
ARG REACT_APP_TESTNET_CHAIN_ID
ARG REACT_APP_TESTNET_CHAIN_NAME
ARG REACT_APP_TESTNET_CHAIN_NETWORK_ID
ARG REACT_APP_TESTNET_CHAIN_NETWORK
ARG REACT_APP_TESTNET_CHAIN_GAS_PRICE
ARG REACT_APP_TESTNET_CHAIN_GAS_LIMIT
ARG REACT_APP_TESTNET_CHAIN_FEE
ARG REACT_APP_TESTNET_CHAIN_PRECISION
ARG REACT_APP_TESTNET_CHAIN_APR_FEE
ARG REACT_APP_TESTNET_CHAIN_VERSION
ARG REACT_APP_TESTNET_DEFAULT_INSTANCE
ARG REACT_APP_TESTNET_WALLETCONNECT_CHAIN_ID
ARG REACT_APP_MAINNET_CHAIN_ID
ARG REACT_APP_MAINNET_CHAIN_NAME
ARG REACT_APP_MAINNET_CHAIN_NETWORK_ID
ARG REACT_APP_MAINNET_CHAIN_NETWORK
ARG REACT_APP_MAINNET_CHAIN_GAS_PRICE
ARG REACT_APP_MAINNET_CHAIN_GAS_LIMIT
ARG REACT_APP_MAINNET_CHAIN_FEE
ARG REACT_APP_MAINNET_CHAIN_PRECISION
ARG REACT_APP_MAINNET_CHAIN_APR_FEE
ARG REACT_APP_MAINNET_CHAIN_VERSION
ARG REACT_APP_MAINNET_DEFAULT_INSTANCE
ARG REACT_APP_MAINNET_WALLETCONNECT_CHAIN_ID

# Set environment variables
ENV REACT_APP_API_URL=$REACT_APP_API_URL \
    REACT_APP_PROJECT_ID=$REACT_APP_PROJECT_ID \
    REACT_APP_RELAY_URL=$REACT_APP_RELAY_URL \
    REACT_APP_KDA_NETWORK_TYPE=$REACT_APP_KDA_NETWORK_TYPE \
    REACT_APP_BASE_URL=$REACT_APP_BASE_URL \
    REACT_APP_ZELCORE_URL=$REACT_APP_ZELCORE_URL \
    REACT_APP_ADMIN_ADDRESS=$REACT_APP_ADMIN_ADDRESS \
    REACT_APP_STRIPE_PUBLISHABLE_KEY=$REACT_APP_STRIPE_PUBLISHABLE_KEY \
    REACT_APP_WALLETCONNECT_BRIDGE_URL=$REACT_APP_WALLETCONNECT_BRIDGE_URL \
    REACT_APP_WALLETCONNECT_CHAIN_ID=$REACT_APP_WALLETCONNECT_CHAIN_ID \
    REACT_APP_TESTNET_CHAIN_ID=$REACT_APP_TESTNET_CHAIN_ID \
    REACT_APP_TESTNET_CHAIN_NAME=$REACT_APP_TESTNET_CHAIN_NAME \
    REACT_APP_TESTNET_CHAIN_NETWORK_ID=$REACT_APP_TESTNET_CHAIN_NETWORK_ID \
    REACT_APP_TESTNET_CHAIN_NETWORK=$REACT_APP_TESTNET_CHAIN_NETWORK \
    REACT_APP_TESTNET_CHAIN_GAS_PRICE=$REACT_APP_TESTNET_CHAIN_GAS_PRICE \
    REACT_APP_TESTNET_CHAIN_GAS_LIMIT=$REACT_APP_TESTNET_CHAIN_GAS_LIMIT \
    REACT_APP_TESTNET_CHAIN_FEE=$REACT_APP_TESTNET_CHAIN_FEE \
    REACT_APP_TESTNET_CHAIN_PRECISION=$REACT_APP_TESTNET_CHAIN_PRECISION \
    REACT_APP_TESTNET_CHAIN_APR_FEE=$REACT_APP_TESTNET_CHAIN_APR_FEE \
    REACT_APP_TESTNET_CHAIN_VERSION=$REACT_APP_TESTNET_CHAIN_VERSION \
    REACT_APP_TESTNET_DEFAULT_INSTANCE=$REACT_APP_TESTNET_DEFAULT_INSTANCE \
    REACT_APP_TESTNET_WALLETCONNECT_CHAIN_ID=$REACT_APP_TESTNET_WALLETCONNECT_CHAIN_ID \
    REACT_APP_MAINNET_CHAIN_ID=$REACT_APP_MAINNET_CHAIN_ID \
    REACT_APP_MAINNET_CHAIN_NAME=$REACT_APP_MAINNET_CHAIN_NAME \
    REACT_APP_MAINNET_CHAIN_NETWORK_ID=$REACT_APP_MAINNET_CHAIN_NETWORK_ID \
    REACT_APP_MAINNET_CHAIN_NETWORK=$REACT_APP_MAINNET_CHAIN_NETWORK \
    REACT_APP_MAINNET_CHAIN_GAS_PRICE=$REACT_APP_MAINNET_CHAIN_GAS_PRICE \
    REACT_APP_MAINNET_CHAIN_GAS_LIMIT=$REACT_APP_MAINNET_CHAIN_GAS_LIMIT \
    REACT_APP_MAINNET_CHAIN_FEE=$REACT_APP_MAINNET_CHAIN_FEE \
    REACT_APP_MAINNET_CHAIN_PRECISION=$REACT_APP_MAINNET_CHAIN_PRECISION \
    REACT_APP_MAINNET_CHAIN_APR_FEE=$REACT_APP_MAINNET_CHAIN_APR_FEE \
    REACT_APP_MAINNET_CHAIN_VERSION=$REACT_APP_MAINNET_CHAIN_VERSION \
    REACT_APP_MAINNET_DEFAULT_INSTANCE=$REACT_APP_MAINNET_DEFAULT_INSTANCE \
    REACT_APP_MAINNET_WALLETCONNECT_CHAIN_ID=$REACT_APP_MAINNET_WALLETCONNECT_CHAIN_ID

RUN npm run build

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION}

# RUN npm install -g npm@latest
RUN npm install -g serve

COPY --from=build-env /usr/src/kryptomerchadmin/build /usr/src/kryptomerchadmin/build

CMD ["serve", "-s", "/usr/src/kryptomerchadmin/build", "-l", "tcp://0.0.0.0:3000"]

EXPOSE 3000