// launchpadAdminPactFunctions.js

const testnetFunctions = {
    transfer: 'n_442d3e11cfe0d39859878e5b1520cd8b8c36e5db.ledger.TRANSFER',
    nftCollectionRequest: 'free.lptest003.nft-collection-request',
    launchCollection: 'free.lptest003.launch-collection',
    createNgCollection: 'free.lptest003.create-ng-collection',
    getCollectionId: 'free.lptest003.get-collection-id',
    createPresale: 'free.lptest003.create-presale',
    createWhitelist: 'free.lptest003.create-whitelist',
    addWlAccounts: 'free.lptest003.add-wl-accounts',
    addPresaleAccounts: 'free.lptest003.add-presale-accounts',
    // createAirdrop: 'free.lptest003.create-airdrop',
    getUnrevealedTokensForCollection: 'free.lptest003.get-unrevealed-tokens-for-collection',
    bulkSyncWithNg: 'free.lptest003.bulk-sync-with-ng',
    getBalance: 'coin.get-balance',
    transferCreate: 'coin.transfer-create',
    addRoles: 'free.lptest003.add-roles',
    addPolicies: 'free.lptest003.add-policies',
    replacePolicies: 'free.lptest003.replace-policies',
    getPolicyOfCollection: 'free.lptest003.get-policy-of-collection',
    updatePrice: 'free.lptest003.update-public-price',
    getCollectionCreator: 'free.lptest003.get-collection-creator',
    getRoyaltyInfo: 'free.lptest003.get-royalty-info',
    isAdmin: 'free.lptest003.IS_ADMIN',
    mintProcess: 'free.lptest003.MINTPROCESS',
    denyCollection: 'free.lptest003.deny-collection',
    createAirdrop: 'free.lptest003.create-airdrop',
    bulkAirdrop: 'free.lptest003.bulk-airdrop',
    getFreeMintEnabled: 'free.lptest003.get-free-mint-enabled',
    getFreeMintClaimed: 'free.lptest003.get-free-mint-claimed',
    getAirdropEnabled: 'free.lptest003.get-airdrop-enabled',
    getAirdropHistory: 'free.lptest003.get-airdrop-history',
    createFreeMint: 'free.lptest003.create-free-mint',
    cancelFreeMint: 'free.lptest003.cancel-free-mint',
    isFreeMintActive: 'free.lptest003.is-free-mint-active',
    getFreeMintTimeStatus: 'free.lptest003.get-free-mint-time-status',
    getTotalSupplyFreeMint: 'free.lptest003.get-total-supply-free-mint',
    getFreeMintClaim: 'free.lptest003.get-free-mint-claim',
    reserveTokenFreeMint: 'free.lptest003.reserve-token-free-mint',
    getCurrentIndexFreeMint: 'free.lptest003.get-current-index-free-mint',
    beforeReservingTokenFreeMint: 'free.lptest003.before-reserving-token-free-mint',
    getCollectionDetails: 'free.lptest003.get-collection-details',
    mintNftCapability: 'free.lptest003.MINT-NFT',
    getTotalMints: 'free.lptest003.get-total-mints',
    getAvailableNormalSupply: 'free.lptest003.get-available-normal-supply',
    getFreeMintsUsed: 'free.lptest003.get-free-mints-used',
    debugFreeMint: 'free.lptest003.debug-free-mint',

};

const mainnetFunctions = {
    transfer: 'n_4e470a97222514a8662dd1219000a0431451b0ee.ledger.TRANSFER',
    nftCollectionRequest: 'free.KMLPV2.nft-collection-request',
    launchCollection: 'free.KMLPV2.launch-collection',
    createNgCollection: 'free.KMLPV2.create-ng-collection',
    getCollectionId: 'free.KMLPV2.get-collection-id',
    createPresale: 'free.KMLPV2.create-presale',
    createWhitelist: 'free.KMLPV2.create-whitelist',
    addWlAccounts: 'free.KMLPV2.add-wl-accounts',
    addPresaleAccounts: 'free.KMLPV2.add-presale-accounts',
    createAirdrop: 'free.KMLPV2.create-airdrop',
    getUnrevealedTokensForCollection: 'free.KMLPV2.get-unrevealed-tokens-for-collection',
    bulkSyncWithNg: 'free.KMLPV2.bulk-sync-with-ng',
    getBalance: 'coin.get-balance',
    transferCreate: 'coin.transfer-create',
    addRoles: 'free.KMLPV2.add-roles',
    addPolicies: 'free.KMLPV2.add-policies',
    replacePolicies: 'free.KMLPV2.replace-policies',
    getPolicyOfCollection: 'free.KMLPV2.get-policy-of-collection',
    updatePrice: 'free.KMLPV2.update-public-price',
    getCollectionCreator: 'free.KMLPV2.get-collection-creator',
    getRoyaltyInfo: 'free.KMLPV2.get-royalty-info',
    isAdmin: 'free.KMLPV2.IS_ADMIN',
    mintProcess: 'free.KMLPV2.MINTPROCESS',
    denyCollection: 'free.KMLPV2.deny-collection',
    createAirdrop: 'free.KMLPV2.create-airdrop',
    bulkAirdrop: 'free.KMLPV2.bulk-airdrop',
    getFreeMintEnabled: 'free.KMLPV2.get-free-mint-enabled',
    getFreeMintClaimed: 'free.KMLPV2.get-free-mint-claimed',
    getAirdropEnabled: 'free.KMLPV2.get-airdrop-enabled',
    getAirdropHistory: 'free.KMLPV2.get-airdrop-history',
    createFreeMint: 'free.KMLPV2.create-free-mint',
    cancelFreeMint: 'free.KMLPV2.cancel-free-mint',
    isFreeMintActive: 'free.KMLPV2.is-free-mint-active',
    getFreeMintTimeStatus: 'free.KMLPV2.get-free-mint-time-status',
    getTotalSupplyFreeMint: 'free.KMLPV2.get-total-supply-free-mint',
    getFreeMintClaim: 'free.KMLPV2.get-free-mint-claim',
    reserveTokenFreeMint: 'free.KMLPV2.reserve-token-free-mint',
    getCurrentIndexFreeMint: 'free.KMLPV2.get-current-index-free-mint',
    beforeReservingTokenFreeMint: 'free.KMLPV2.before-reserving-token-free-mint',
    getCollectionDetails: 'free.KMLPV2.get-collection-details',
    mintNftCapability: 'free.KMLPV2.MINT-NFT',
    getTotalMints: 'free.KMLPV2.get-total-mints',
    getAvailableNormalSupply: 'free.KMLPV2.get-available-normal-supply',
    getFreeMintsUsed: 'free.KMLPV2.get-free-mints-used',
    debugFreeMint: 'free.KMLPV2.debug-free-mint',
};

const networkType = process.env.REACT_APP_KDA_NETWORK_TYPE || 'testnet';

const launchpadPactFunctions = networkType === 'mainnet' ? mainnetFunctions : testnetFunctions;

export default launchpadPactFunctions;