# name: Build and Analyze
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   build-and-test:
#     name: Build and Test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
      
#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '20'
      
#       - name: Install dependencies
#         run: npm install
      
#       - name: Build project
#         run: npm run build
#         env:
#           CI: false
      
#       # - name: Run tests with coverage
#       #   run: yarn test --coverage
      
#       # - name: Upload coverage reports to Codecov
#       #   uses: codecov/codecov-action@v3
#       #   env:
#       #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#   sonarcloud:
#     name: SonarCloud
#     runs-on: ubuntu-latest
#     needs: build-and-test
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       # - name: Set up Node.js
#       #   uses: actions/setup-node@v1
#       #   with:
#       #     node-version: '20' 
#       # - name: Install dependencies
#       #   run: npm install
#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         with:
#           args: >
#             -Dsonar.organization=rahulb15
#             -Dsonar.projectKey=rahulb15_K-Admin-New

#   docker:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest
#     needs: [build-and-test, sonarcloud]
#     steps:
#       - uses: actions/checkout@v4
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
      
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/kryptomerchadmin:latest
#           build-args: |
#             REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
#             REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }}
#             REACT_APP_RELAY_URL=${{ secrets.REACT_APP_RELAY_URL }}
#             REACT_APP_KDA_NETWORK_TYPE=${{ secrets.REACT_APP_KDA_NETWORK_TYPE }}
#             REACT_APP_KDA_CHAIN_ID=${{ secrets.REACT_APP_KDA_CHAIN_ID }}
#             REACT_APP_KDA_GAS_PRICE=${{ secrets.REACT_APP_KDA_GAS_PRICE }}
#             REACT_APP_KDA_GAS_LIMIT=${{ secrets.REACT_APP_KDA_GAS_LIMIT }}
#             REACT_APP_KDA_PRECISION=${{ secrets.REACT_APP_KDA_PRECISION }}
#             REACT_APP_KDA_NETWORK_ID=${{ secrets.REACT_APP_KDA_NETWORK_ID }}
#             REACT_APP_KDA_FEE=${{ secrets.REACT_APP_KDA_FEE }}
#             REACT_APP_APR_FEE=${{ secrets.REACT_APP_APR_FEE }}
#             REACT_APP_KDA_NETWORK=${{ secrets.REACT_APP_KDA_NETWORK }}
#             REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}
#             REACT_APP_ZELCORE_URL=${{ secrets.REACT_APP_ZELCORE_URL }}
#             REACT_APP_STRIPE_PUBLISHABLE_KEY=${{ secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY }}



name: Build and Analyze
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
        env:
          CI: false

  # sonarcloud:
  #   name: SonarCloud
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       with:
  #         args: >
  #           -Dsonar.organization=rahulb15
  #           -Dsonar.projectKey=rahulb15_K-Admin-New

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    # needs: [build-and-test, sonarcloud]
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/kryptomerchadmin:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kryptomerchmainadmin:latest
          build-args: |
            REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
            REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }}
            REACT_APP_RELAY_URL=${{ secrets.REACT_APP_RELAY_URL }}
            REACT_APP_KDA_NETWORK_TYPE=${{ secrets.REACT_APP_KDA_NETWORK_TYPE }}
            REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}
            REACT_APP_ZELCORE_URL=${{ secrets.REACT_APP_ZELCORE_URL }}
            REACT_APP_ADMIN_ADDRESS=${{ secrets.REACT_APP_ADMIN_ADDRESS }}
            REACT_APP_STRIPE_PUBLISHABLE_KEY=${{ secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY }}
            REACT_APP_WALLETCONNECT_BRIDGE_URL=${{ secrets.REACT_APP_WALLETCONNECT_BRIDGE_URL }}
            REACT_APP_WALLETCONNECT_CHAIN_ID=${{ secrets.REACT_APP_WALLETCONNECT_CHAIN_ID }}
            REACT_APP_TESTNET_CHAIN_ID=${{ secrets.REACT_APP_TESTNET_CHAIN_ID }}
            REACT_APP_TESTNET_CHAIN_NAME=${{ secrets.REACT_APP_TESTNET_CHAIN_NAME }}
            REACT_APP_TESTNET_CHAIN_NETWORK_ID=${{ secrets.REACT_APP_TESTNET_CHAIN_NETWORK_ID }}
            REACT_APP_TESTNET_CHAIN_NETWORK=${{ secrets.REACT_APP_TESTNET_CHAIN_NETWORK }}
            REACT_APP_TESTNET_CHAIN_GAS_PRICE=${{ secrets.REACT_APP_TESTNET_CHAIN_GAS_PRICE }}
            REACT_APP_TESTNET_CHAIN_GAS_LIMIT=${{ secrets.REACT_APP_TESTNET_CHAIN_GAS_LIMIT }}
            REACT_APP_TESTNET_CHAIN_FEE=${{ secrets.REACT_APP_TESTNET_CHAIN_FEE }}
            REACT_APP_TESTNET_CHAIN_PRECISION=${{ secrets.REACT_APP_TESTNET_CHAIN_PRECISION }}
            REACT_APP_TESTNET_CHAIN_APR_FEE=${{ secrets.REACT_APP_TESTNET_CHAIN_APR_FEE }}
            REACT_APP_TESTNET_CHAIN_VERSION=${{ secrets.REACT_APP_TESTNET_CHAIN_VERSION }}
            REACT_APP_TESTNET_DEFAULT_INSTANCE=${{ secrets.REACT_APP_TESTNET_DEFAULT_INSTANCE }}
            REACT_APP_TESTNET_WALLETCONNECT_CHAIN_ID=${{ secrets.REACT_APP_TESTNET_WALLETCONNECT_CHAIN_ID }}
            REACT_APP_MAINNET_CHAIN_ID=${{ secrets.REACT_APP_MAINNET_CHAIN_ID }}
            REACT_APP_MAINNET_CHAIN_NAME=${{ secrets.REACT_APP_MAINNET_CHAIN_NAME }}
            REACT_APP_MAINNET_CHAIN_NETWORK_ID=${{ secrets.REACT_APP_MAINNET_CHAIN_NETWORK_ID }}
            REACT_APP_MAINNET_CHAIN_NETWORK=${{ secrets.REACT_APP_MAINNET_CHAIN_NETWORK }}
            REACT_APP_MAINNET_CHAIN_GAS_PRICE=${{ secrets.REACT_APP_MAINNET_CHAIN_GAS_PRICE }}
            REACT_APP_MAINNET_CHAIN_GAS_LIMIT=${{ secrets.REACT_APP_MAINNET_CHAIN_GAS_LIMIT }}
            REACT_APP_MAINNET_CHAIN_FEE=${{ secrets.REACT_APP_MAINNET_CHAIN_FEE }}
            REACT_APP_MAINNET_CHAIN_PRECISION=${{ secrets.REACT_APP_MAINNET_CHAIN_PRECISION }}
            REACT_APP_MAINNET_CHAIN_APR_FEE=${{ secrets.REACT_APP_MAINNET_CHAIN_APR_FEE }}
            REACT_APP_MAINNET_CHAIN_VERSION=${{ secrets.REACT_APP_MAINNET_CHAIN_VERSION }}
            REACT_APP_MAINNET_DEFAULT_INSTANCE=${{ secrets.REACT_APP_MAINNET_DEFAULT_INSTANCE }}
            REACT_APP_MAINNET_WALLETCONNECT_CHAIN_ID=${{ secrets.REACT_APP_MAINNET_WALLETCONNECT_CHAIN_ID }}